
# This file is automatically generated, you probably don't want to edit this

#' @importFrom jmvcore Options
#' @importFrom R6 R6Class
DecisionTreeOptions <- R6::R6Class(
    "DecisionTreeOptions",
    inherit = jmvcore::Options,
    public = list(
        initialize = function(
            dep = NULL,
            indep = NULL,
            split = 75,
            method = "Class",
            Control = 15, ...) {

            super$initialize(
                package='MTUclassification',
                name='DecisionTree',
                requiresData=TRUE,
                ...)
        
            private$..dep <- jmvcore::OptionVariable$new(
                "dep",
                dep)
            private$..indep <- jmvcore::OptionVariables$new(
                "indep",
                indep)
            private$..split <- jmvcore::OptionNumber$new(
                "split",
                split,
                min=60,
                max=90,
                default=75)
            private$..method <- jmvcore::OptionList$new(
                "method",
                method,
                options=list(
                    "Class",
                    "Anova"),
                default="Class")
            private$..Control <- jmvcore::OptionNumber$new(
                "Control",
                Control,
                min=1,
                max=100,
                default=15)
        
            self$.addOption(private$..dep)
            self$.addOption(private$..indep)
            self$.addOption(private$..split)
            self$.addOption(private$..method)
            self$.addOption(private$..Control)
        }),
    active = list(
        dep = function() private$..dep$value,
        indep = function() private$..indep$value,
        split = function() private$..split$value,
        method = function() private$..method$value,
        Control = function() private$..Control$value),
    private = list(
        ..dep = NA,
        ..indep = NA,
        ..split = NA,
        ..method = NA,
        ..Control = NA)
)

#' @import jmvcore
#' @importFrom R6 R6Class
DecisionTreeResults <- R6::R6Class(
    inherit = jmvcore::Group,
    active = list(
        text = function() private$..text,
        plot = function() private$..plot),
    private = list(
        ..text = NA,
        ..plot = NA),
    public=list(
        initialize=function(options) {
            super$initialize(options=options, name="", title="Classification using Decision Tree")
            private$..text <- jmvcore::Preformatted$new(
                options=options,
                name="text",
                title="Classification using Decision Tree")
            private$..plot <- jmvcore::Image$new(
                options=options,
                name="plot",
                title="Plot of Decision Tree",
                width=375,
                height=425,
                renderFun=".plot")
            self$add(private$..text)
            self$add(private$..plot)}))

#' @importFrom jmvcore Analysis
#' @importFrom R6 R6Class
DecisionTreeBase <- R6::R6Class(
    "DecisionTreeBase",
    inherit = jmvcore::Analysis,
    public = list(
        initialize = function(options, data=NULL, datasetId="", analysisId="", revision=0) {
            super$initialize(
                package = 'MTUclassification',
                name = 'DecisionTree',
                version = c(1,0,0),
                options = options,
                results = DecisionTreeResults$new(options=options),
                data = data,
                datasetId = datasetId,
                analysisId = analysisId,
                revision = revision,
                pause = NULL,
                completeWhenFilled = FALSE)
        }))

#' Classification using Decision Tree
#'
#' 
#' @param data .
#' @param dep .
#' @param indep .
#' @param split .
#' @param method .
#' @param Control .
#' @export
DecisionTree <- function(
    data,
    dep,
    indep,
    split = 75,
    method = "Class",
    Control = 15) {

    options <- DecisionTreeOptions$new(
        dep = dep,
        indep = indep,
        split = split,
        method = method,
        Control = Control)

    results <- DecisionTreeResults$new(
        options = options)

    analysis <- DecisionTreeClass$new(
        options = options,
        data = data)

    analysis$run()

    analysis$results
}
