
# This file is automatically generated, you probably don't want to edit this

#' @importFrom jmvcore Options
#' @importFrom R6 R6Class
knnOptions <- R6::R6Class(
    "knnOptions",
    inherit = jmvcore::Options,
    public = list(
        initialize = function(
            dv = NULL,
            idv = NULL,
            k = 2,
            split = 75,
            isNorm = FALSE, ...) {

            super$initialize(
                package='MTUclassification',
                name='knn',
                requiresData=TRUE,
                ...)
        
            private$..dv <- jmvcore::OptionVariable$new(
                "dv",
                dv)
            private$..idv <- jmvcore::OptionVariables$new(
                "idv",
                idv)
            private$..k <- jmvcore::OptionInteger$new(
                "k",
                k,
                default=2,
                min=1)
            private$..split <- jmvcore::OptionInteger$new(
                "split",
                split,
                default=75,
                min=50,
                max=90)
            private$..isNorm <- jmvcore::OptionBool$new(
                "isNorm",
                isNorm,
                default=FALSE)
        
            self$.addOption(private$..dv)
            self$.addOption(private$..idv)
            self$.addOption(private$..k)
            self$.addOption(private$..split)
            self$.addOption(private$..isNorm)
        }),
    active = list(
        dv = function() private$..dv$value,
        idv = function() private$..idv$value,
        k = function() private$..k$value,
        split = function() private$..split$value,
        isNorm = function() private$..isNorm$value),
    private = list(
        ..dv = NA,
        ..idv = NA,
        ..k = NA,
        ..split = NA,
        ..isNorm = NA)
)

#' @import jmvcore
#' @importFrom R6 R6Class
knnResults <- R6::R6Class(
    inherit = jmvcore::Group,
    active = list(
        predicted = function() private$..predicted,
        actual = function() private$..actual,
        confMat = function() private$..confMat,
        footer = function() private$..footer),
    private = list(
        ..predicted = NA,
        ..actual = NA,
        ..confMat = NA,
        ..footer = NA),
    public=list(
        initialize=function(options) {
            super$initialize(options=options, name="", title="K Nearest Neighbor")
            private$..predicted <- jmvcore::Preformatted$new(
                options=options,
                name="predicted",
                title="Predicted for test set")
            private$..actual <- jmvcore::Preformatted$new(
                options=options,
                name="actual",
                title="Actual for test set")
            private$..confMat <- jmvcore::Preformatted$new(
                options=options,
                name="confMat",
                title="Model Evaluation")
            private$..footer <- jmvcore::Preformatted$new(
                options=options,
                name="footer",
                title="About")
            self$add(private$..predicted)
            self$add(private$..actual)
            self$add(private$..confMat)
            self$add(private$..footer)}))

#' @importFrom jmvcore Analysis
#' @importFrom R6 R6Class
knnBase <- R6::R6Class(
    "knnBase",
    inherit = jmvcore::Analysis,
    public = list(
        initialize = function(options, data=NULL, datasetId="", analysisId="", revision=0) {
            super$initialize(
                package = 'MTUclassification',
                name = 'knn',
                version = c(1,0,0),
                options = options,
                results = knnResults$new(options=options),
                data = data,
                datasetId = datasetId,
                analysisId = analysisId,
                revision = revision,
                pause = NULL,
                completeWhenFilled = FALSE)
        }))

#' K Nearest Neighbor
#'
#' 
#' @param data .
#' @param dv .
#' @param idv .
#' @param k .
#' @param split .
#' @param isNorm .
#' @export
knn <- function(
    data,
    dv,
    idv,
    k = 2,
    split = 75,
    isNorm = FALSE) {

    options <- knnOptions$new(
        dv = dv,
        idv = idv,
        k = k,
        split = split,
        isNorm = isNorm)

    results <- knnResults$new(
        options = options)

    analysis <- knnClass$new(
        options = options,
        data = data)

    analysis$run()

    analysis$results
}
