
# This file is automatically generated, you probably don't want to edit this

#' @importFrom jmvcore Options
#' @importFrom R6 R6Class
RandomForestOptions <- R6::R6Class(
    "RandomForestOptions",
    inherit = jmvcore::Options,
    public = list(
        initialize = function(
            dep = NULL,
            indep = NULL,
            split = 75,
            ntree = 500, ...) {

            super$initialize(
                package='MTUclassification',
                name='RandomForest',
                requiresData=TRUE,
                ...)
        
            private$..dep <- jmvcore::OptionVariable$new(
                "dep",
                dep)
            private$..indep <- jmvcore::OptionVariables$new(
                "indep",
                indep)
            private$..split <- jmvcore::OptionNumber$new(
                "split",
                split,
                min=60,
                max=90,
                default=75)
            private$..ntree <- jmvcore::OptionNumber$new(
                "ntree",
                ntree,
                min=100,
                max=1000,
                default=500)
        
            self$.addOption(private$..dep)
            self$.addOption(private$..indep)
            self$.addOption(private$..split)
            self$.addOption(private$..ntree)
        }),
    active = list(
        dep = function() private$..dep$value,
        indep = function() private$..indep$value,
        split = function() private$..split$value,
        ntree = function() private$..ntree$value),
    private = list(
        ..dep = NA,
        ..indep = NA,
        ..split = NA,
        ..ntree = NA)
)

#' @import jmvcore
#' @importFrom R6 R6Class
RandomForestResults <- R6::R6Class(
    inherit = jmvcore::Group,
    active = list(
        text = function() private$..text),
    private = list(
        ..text = NA),
    public=list(
        initialize=function(options) {
            super$initialize(options=options, name="", title="Classification using Random Forest")
            private$..text <- jmvcore::Preformatted$new(
                options=options,
                name="text",
                title="Classification using Random Forest")
            self$add(private$..text)}))

#' @importFrom jmvcore Analysis
#' @importFrom R6 R6Class
RandomForestBase <- R6::R6Class(
    "RandomForestBase",
    inherit = jmvcore::Analysis,
    public = list(
        initialize = function(options, data=NULL, datasetId="", analysisId="", revision=0) {
            super$initialize(
                package = 'MTUclassification',
                name = 'RandomForest',
                version = c(1,0,0),
                options = options,
                results = RandomForestResults$new(options=options),
                data = data,
                datasetId = datasetId,
                analysisId = analysisId,
                revision = revision,
                pause = NULL,
                completeWhenFilled = FALSE)
        }))

#' Classification using Random Forest
#'
#' 
#' @param data .
#' @param dep .
#' @param indep .
#' @param split .
#' @param ntree .
#' @export
RandomForest <- function(
    data,
    dep,
    indep,
    split = 75,
    ntree = 500) {

    options <- RandomForestOptions$new(
        dep = dep,
        indep = indep,
        split = split,
        ntree = ntree)

    results <- RandomForestResults$new(
        options = options)

    analysis <- RandomForestClass$new(
        options = options,
        data = data)

    analysis$run()

    analysis$results
}
